### ISSUE TITLE
multi line DefaultCenter and DefaultHeader broken

### ISSUE THREAD

**Issue by xbipin** [pterm/pterm#209]
when i run the below code to have a 2 line header or just center block it doesnt work

pterm.DefaultCenter.Print(pterm.DefaultHeader.WithFullWidth().WithBackgroundStyle(pterm.NewStyle(pterm.BgLightBlue)).WithMargin(10).Sprint("First line\nsecond Line"))

**Comment by xbipin** [comment]
to add to this, even with single line text if you resize the window then it again breaks

**Comment by MarvinJWendt** [comment]
Hi @xbipin, thanks for reporting the issue! I am currently writing a fix for it, I just have to release it. I'll let you know when it's released.
![image](https://user-images.githubusercontent.com/31022056/120077409-9e6f4e00-c0aa-11eb-9db9-3278f910bd85.png)

> to add to this, even with single line text if you resize the window then it again breaks

We cannot handle terminal resizing with already printed text.

**Comment by MarvinJWendt** [comment]
The fix was released with [`v0.12.19`](https://github.com/pterm/pterm/releases/tag/v0.12.19).

**Comment by xbipin** [comment]
it still doesnt work well with pterm.DefaultHeader.WithFullWidth(), the background colored box doesnt span full width

**Comment by MarvinJWendt** [comment]
@floaust is working on a couple changes, which I think will also fix this.
