### ISSUE TITLE
MultiPrinter crashes

### ISSUE THREAD

**Issue by jurelou** [pterm/pterm#626]
Hi, I'm trying to bind a  `Logger` and a `ProgressBar` to the same `DefaultMultiPrinter`

When binding the logger i have the following errors:

```
panic: runtime error: index out of range [-1]

goroutine 20 [running]:
github.com/pterm/pterm.(*MultiPrinter).getString(0xc00020e060?)
        <project>/vendor/github.com/pterm/pterm/multi_live_printer.go:67 +0x1c6
github.com/pterm/pterm.(*MultiPrinter).Start.func1()
        <project>/vendor/github.com/pterm/pterm/multi_live_printer.go:88 +0x25
atomicgo.dev/schedule.Every.func1()
        <project>/vendor/atomicgo.dev/schedule/schedule.go:106 +0x8f
created by atomicgo.dev/schedule.Every in goroutine 1
        <project>/vendor/atomicgo.dev/schedule/schedule.go:102 +0x15b
exit status 2
```

i'm using pterm v1.12.76

**Comment by MarvinJWendt** [comment]
In theory, the logger should work without needing a `MultiPrinter`, but it doesn't.
I'll fix that.

**Comment by MarvinJWendt** [comment]
I fixed it, you should be able to do:

```go
func main() {
	logger := pterm.DefaultLogger.WithLevel(pterm.LogLevelInfo)

	pb, _ := pterm.DefaultProgressbar.WithTitle("Example...").Start()
	for i := 0; i < 100; i++ {
		pb.Increment()
		time.Sleep(time.Millisecond * 50)

		if i%10 == 0 {
			logger.Info("This is a log message!")
		}
	}

	pb.Stop()
}
```

The fix will be released in the next hour. Thanks for reporting the issue!

**Comment by MarvinJWendt** [comment]
Could you still post a code sample for the bug in `MultiPrinter`? It shouldn't panic, so I'll tackle that separately :)

**Comment by jurelou** [comment]
Hi, thanks for the Quick fix!
At least it will work with a single printer/progressbar but i guess it will still crash with a single printer and multiple progressbars.

The bug was found in a huge codebase, i will try to generate a code sample

**Comment by MarvinJWendt** [comment]
That would be nice. Somehow the fix didn't deploy yet, seems like the build pipeline is broken (again). Will fix it soon.

**Comment by MarvinJWendt** [comment]
Hi, I merged the fix for now.

> The bug was found in a huge codebase, i will try to generate a code sample

Please open a new issue when you provide a code sample :)

**Comment by zupo** [comment]
Hey, any chance to get a new release cut, so I can use this fix? Perfectly understandable if you're busy and can't do it ATM.
